//** This file was code generated by GoT. DO NOT EDIT. ***

package form

import (
	"context"
	"html"
	"io"

	"github.com/goradd/html5tag"
	"github.com/goradd/serve/control/textbox"
)

// AddHeadTags adds items that will appear in the head tag of the html page.
func (ctrl *TextboxesForm1) AddHeadTags() {
	ctrl.FormBase.AddHeadTags()
	if "Textboxes 1" != "" {
		ctrl.Form().Page().SetTitle("Textboxes 1")
	}

	// deal with body attributes too
	ctrl.Form().Page().BodyAttributes = ``
}

// DrawTemplate draws the content of the matching form's template file.
func (ctrl *TextboxesForm1) DrawTemplate(ctx context.Context, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `<h1>`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, html.EscapeString(ctrl.T(`Textboxes 1`))); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `</h1>
<label for="standard">`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, html.EscapeString(ctrl.T(`Standard`))); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `</label>`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `
`); err != nil {
		return
	}

	if `` == "" {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Form().GetControl("standard").Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	} else {

		if _, err = io.WriteString(_w, `    `); err != nil {
			return
		}
		ctrl.Form().GetControl("standard").MergeAttributes(html5tag.Attributes{}).Draw(ctx, _w)
		if _, err = io.WriteString(_w, `
`); err != nil {
			return
		}

	}

	return
}

// createTemplateControls creates the controls defined in the template.
func (ctrl *TextboxesForm1) createTemplateControls(ctx context.Context) {

	textbox.NewTextbox(ctrl, "standard").
		MergeAttributes(html5tag.Attributes{"type": "text"})

}

func (ctrl *TextboxesForm1) standardTextbox() *textbox.Textbox {
	if i := ctrl.Form().GetControl("standard"); i != nil {
		if c, ok := i.(*textbox.Textbox); !ok {
			panic(`control with id "standard" was not a textbox.Textbox`)
		} else {
			return c
		}
	}
	panic(`control not found: standard`)
}
